# Generated by Django 4.1.2 on 2022-10-25 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_games_points'),
        ('management', '0002_account_name_account_nmec'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bars'),
        ),
    ]
