# Generated by Django 4.1.2 on 2022-10-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
