# Generated by Django 4.1.2 on 2022-10-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin_timestamp_teams_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsbars',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
