# Generated by Django 4.1.2 on 2022-10-17 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_teamsbars_points'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
