# Generated by Django 4.1.2 on 2022-10-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_teams_drinks_teams_puked_teamsbars_drinks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsbars',
            name='won_game',
            field=models.BooleanField(default=False),
        ),
    ]
