# Generated by Django 4.1.2 on 2022-10-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_teamsbars_won_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bars',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.games'),
        ),
        migrations.AlterField(
            model_name='prizes',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.teams'),
        ),
    ]
