# Generated by Django 4.1.2 on 2022-10-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_teams_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='qr_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
