# Generated by Django 4.1.2 on 2022-10-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bars_points_games_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='drinks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamsbars',
            name='puked',
            field=models.IntegerField(default=0),
        ),
    ]
