# Generated by Django 4.1.2 on 2022-10-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_members_drinks_alter_teamsbars_puked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bars',
            name='location',
        ),
        migrations.AddField(
            model_name='bars',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bars',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bars',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
