# Generated by Django 4.1.2 on 2022-10-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_bars_location_bars_address_bars_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bars',
            name='drinks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bars',
            name='puked',
            field=models.IntegerField(default=0),
        ),
    ]
