# Generated by Django 4.1.2 on 2022-10-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bars_drinks_bars_puked'),
    ]

    operations = [
        migrations.AddField(
            model_name='bars',
            name='visitd',
            field=models.IntegerField(default=0),
        ),
    ]
