# Generated by Django 4.1.2 on 2022-10-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_bars_visitd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bars',
            old_name='visitd',
            new_name='visited',
        ),
    ]
