# Generated by Django 4.1.2 on 2022-10-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_bars_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bars',
            name='picture',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
