# Generated by Django 4.1.2 on 2022-10-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_bars_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bars',
            name='picture',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
