# Generated by Django 4.1.2 on 2022-10-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_bars_picture_alter_games_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='email',
        ),
        migrations.AddField(
            model_name='teams',
            name='phone',
            field=models.IntegerField(default=912345678),
            preserve_default=False,
        ),
    ]
