# Generated by Django 4.1.2 on 2022-10-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_bars_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
