const UA_COURSES = [
    "Administração Pública",
    "Biologia",
    "Biologia e Geologia",
    "Bioquímica",
    "Biotecnologia",
    "Ciências Biomédicas",
    "Ciências do Mar",
    "Contabilidade",
    "Contabilidade à Distância",
    "Contabilidade pós-laboral",
    "Design",
    "Design de Produto e Tecnologia",
    "Economia",
    "Educação Básica",
    "Eletrónica e Mecânica Industrial",
    "Enfermagem",
    "Engenharia Aeroespacial",
    "Engenharia Biomédica",
    "Engenharia Civil",
    "Engenharia Computacional",
    "Engenharia de Automação Industrial",
    "Engenharia de Computadores e Informática",
    "Engenharia de Materiais",
    "Engenharia do Ambiente",
    "Engenharia e Gestão Industrial",
    "Engenharia Eletrotécnica",
    "Engenharia Eletrotécnica e de Computadores",
    "Engenharia Física",
    "Engenharia Informática",
    "Engenharia Mecânica",
    "Engenharia Química",
    "Finanças",
    "Finanças pós-laboral",
    "Física",
    "Fisioterapia",
    "Geologia",
    "Gestão",
    "Gestão Comercial",
    "Gestão da Qualidade",
    "Gestão e Planeamento em Turismo",
    "Gestão Pública",
    "Imagem Médica e Radioterapia",
    "Línguas e Estudos Editoriais",
    "Línguas e Relações Empresariais",
    "Línguas, Literaturas e Culturas",
    "Marketing",
    "Marketing pós-laboral",
    "Matemática",
    "Meteorologia, Oceanografia e Geofísica",
    "Multimédia e Tecnologias da Comunicação",
    "Música",
    "Novas Tecnologias da Comunicação",
    "Psicologia",
    "Química",
    "Reabilitação do Património",
    "Secretariado e Comunicação Empresarial",
    "Tecnologia e Sistemas de Produção",
    "Tecnologias da Informação",
    "Terapia da Fala",
    "Tradução",
    "Administração e Gestão Pública ",
    "Administração e Politicas Públicas",
    "Ambiente e Saúde",
    "Assessoria de Direção e Comunicação nas Organizações",
    "Bioinformática Clínica",
    "Biologia Aplicada",
    "Biologia Marinha Aplicada",
    "Biologia Molecular e Celular",
    "Biomedicina Molecular",
    "Bioquímica",
    "Biotecnologia",
    "Cibersegurança",
    "Ciência de Dados",
    "Ciência de Dados para Ciências Sociais",
    "Ciência Política",
    "Ciências do Mar e da Atmosfera",
    "Competitividade e Desenvolvimento de Negócios",
    "Comunicação Audiovisual Para Novos Média",
    "Comunicação e Tecnologias Web",
    "Comunicação Multimédia ",
    "Construção e Reabilitação de Infraestruturas de Transporte ",
    "Contabilidade",
    "Contabilidade e Controlo de Gestão",
    "Criação Artística Contemporânea",
    "Desenvolvimento de Jogos Digitais",
    "Design",
    "Ecologia Aplicada",
    "Economia",
    "Eco-toxicologia e Análise de Risco",
    "Educação e Formação",
    "Educação Pré-Escolar e Ensino no 1º Ciclo do Ensino Básico",
    "Enfermagem Comunitária, na Área de Enfermagem de Saúde Familiar",
    "Engenharia Biomédica",
    "Engenharia Civil",
    "Engenharia Computacional",
    "Engenharia da Soldadura",
    "Engenharia de Automação Industrial",
    "Engenharia de Computadores e Telemática",
    "Engenharia de Materiais",
    "Engenharia do Ambiente",
    "Engenharia e Design de Produto",
    "Engenharia e Gestão Industrial",
    "Engenharia Eletrónica e Telecomunicações",
    "Engenharia Física",
    "Engenharia Geológica",
    "Engenharia Informática",
    "Engenharia Mecânica",
    "Engenharia Química",
    "Ensino de Música",
    "Estatística Médica",
    "Estudos Ambientais ",
    "Estudos Chineses",
    "Estudos Editoriais",
    "Finanças",
    "Física",
    "Fisioterapia",
    "Geomateriais e Recursos Geológicos",
    "Gerontologia Aplicada",
    "Gestão",
    "Gestão Comercial",
    "Gestão da Investigação Clínica",
    "Gestão da Qualidade Total",
    "Gestão e Negócios Digitais ",
    "Gestão e Planeamento em Turismo",
    "Informática Aplicada",
    "Línguas e Relações Empresariais",
    "Manufatura Aditiva",
    "Marketing",
    "Marketing e Comunicação Digital",
    "Matemática e Aplicações",
    "Matemática para Professores",
    "Materiais e Dispositivos Biomédicos",
    "Microbiologia",
    "Mobilidade Inteligente",
    "Música",
    "Planeamento Regional e Urbano",
    "Português Língua Estrangeira/Língua Segunda",
    "Produto e Tecnologia Digital",
    "Projeto de Estruturas",
    "Psicologia da Saúde e Neuropsicologia",
    "Psicologia da Saúde e Reabilitação Neuropsicológica ",
    "Química",
    "Reabilitação do Património",
    "Robótica e Sistemas Inteligentes",
    "Sistemas de Comunicação Aeroespaciais",
    "Sistemas Energéticos Sustentáveis",
    "Tecnologias da Imagem Médica",
    "Terapia da Fala",
    "Tradução Especializada"
];